name = "tutasnack-frontend"
compatibility_date = "2026-05-28"
account_id = "15f8d1f70095da5af30f6a6f15f7d3c0"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
NUXT_PUBLIC_API_BASE_URL = "https://tutasnack-backend.rezanurrochmat.workers.dev/api"
